language: ruby
rvm:
  - "2.1.3"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database phonebanking_test;' -U postgres
  - psql -U postgres -q -d phonebanking_test -f db/structure.sql

script: 'bundle exec rake'
